import esbuild from 'esbuild';
import process from 'node:process';
import builtins from 'builtin-modules';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
If you want to view the source, please visit the github repository.
*/
`;

const prod = process.argv[2] === 'production';

/**
 * Replace every `mathjax-full/*` import with an empty CommonJS module.
 *
 * Marp Core wires both KaTeX and MathJax. We force `math: 'katex'` in our
 * engine wrapper, so MathJax is never executed — but it would still be pulled
 * into the bundle (megabytes of code) without this shim.
 */
const stripMathjaxPlugin = {
  name: 'strip-mathjax',
  setup(build) {
    build.onResolve({ filter: /^mathjax-full(\/.*)?$/ }, (args) => ({
      path: args.path,
      namespace: 'stripped-mathjax',
    }));
    build.onLoad({ filter: /.*/, namespace: 'stripped-mathjax' }, () => ({
      contents:
        'module.exports = new Proxy({}, { get: () => () => { throw new Error("mathjax-full was stripped from the bundle"); } });',
      loader: 'js',
    }));
  },
};

/**
 * Marp Core pulls in PostCSS and optional source-map helpers. Those helpers
 * reference Node built-ins even though this plugin never needs filesystem
 * source-map loading at runtime. Obsidian Mobile cannot load plugin bundles
 * that contain bare `require("fs")`, so provide small browser-safe shims.
 */
const shimNodeBuiltinsPlugin = {
  name: 'shim-node-builtins',
  setup(build) {
    const shim = (name, contents) => {
      build.onResolve({ filter: new RegExp(`^(node:)?${name}$`) }, () => ({
        path: name,
        namespace: 'node-shim',
      }));
      build.onLoad({ filter: new RegExp(`^${name}$`), namespace: 'node-shim' }, () => ({
        contents,
        loader: 'js',
      }));
    };

    shim(
      'fs',
      `
        export function existsSync() { return false; }
        export function readFileSync() { throw new Error('fs.readFileSync is not available in Obsidian Mobile'); }
      `
    );
    shim(
      'path',
      `
        export const sep = '/';
        export function dirname(path) {
          const normalized = String(path || '').replace(/\\\\/g, '/');
          const index = normalized.lastIndexOf('/');
          return index <= 0 ? (index === 0 ? '/' : '.') : normalized.slice(0, index);
        }
        export function join(...parts) {
          return parts.filter(Boolean).join('/').replace(/\\/+/g, '/');
        }
        export function resolve(...parts) {
          return join(...parts);
        }
        export function isAbsolute(path) {
          return String(path || '').startsWith('/');
        }
      `
    );
    shim(
      'url',
      `
        export function fileURLToPath(url) {
          const value = String(url || '');
          return value.startsWith('file://') ? decodeURIComponent(value.slice(7)) : value;
        }
        export function pathToFileURL(path) {
          return new URL('file://' + String(path || ''));
        }
      `
    );
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins.filter((name) => !['fs', 'path', 'url'].includes(name)),
  ],
  plugins: [stripMathjaxPlugin, shimNodeBuiltinsPlugin],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  minify: prod,
  outfile: 'main.js',
  platform: 'browser',
  conditions: ['browser', 'module', 'import', 'default'],
});

if (prod) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
