import esbuild from 'esbuild';
import process from 'node:process';
import builtins from 'builtin-modules';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
If you want to view the source, please visit the github repository.
*/
`;

const prod = process.argv[2] === 'production';

/**
 * Replace every `mathjax-full/*` import with an empty CommonJS module.
 *
 * Marp Core wires both KaTeX and MathJax. We force `math: 'katex'` in our
 * engine wrapper, so MathJax is never executed — but it would still be pulled
 * into the bundle (megabytes of code) without this shim.
 */
const stripMathjaxPlugin = {
  name: 'strip-mathjax',
  setup(build) {
    build.onResolve({ filter: /^mathjax-full(\/.*)?$/ }, (args) => ({
      path: args.path,
      namespace: 'stripped-mathjax',
    }));
    build.onLoad({ filter: /.*/, namespace: 'stripped-mathjax' }, () => ({
      contents:
        'module.exports = new Proxy({}, { get: () => () => { throw new Error("mathjax-full was stripped from the bundle"); } });',
      loader: 'js',
    }));
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  plugins: [stripMathjaxPlugin],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  minify: prod,
  outfile: 'main.js',
  platform: 'browser',
  conditions: ['browser', 'module', 'import', 'default'],
});

if (prod) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
